In [1]:
import tensorflow as tf
from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import joblib

In [2]:
df = pd.read_csv('D:\CDAC_PUNE_PROJECT\\combined.csv',index_col=0)

In [3]:
df.head()

reviewText  class
0  This is a  well fitting case that really helps...      1
1  This is my first IEM which are not UE. I love ...      0
2  I am satisfied, but placing my phone in a pant...      1
3  This case can be found listed as 7.25&#34; hig...      0
4  This is very nice and very smart.  The other e...      1

In [4]:
cleaned=[]
def clean_text(sent):

    cleaned.append(simple_preprocess(sent))

In [5]:
train_df,test_df=train_test_split(df,stratify=df['class'],test_size=0.2,random_state=0)

In [6]:
train_df.count(),test_df.count()

(reviewText    1440000
 class         1440000
 dtype: int64,
 reviewText    360000
 class         360000
 dtype: int64)

In [7]:
train_df['class'].value_counts(),test_df['class'].value_counts()

(class
 0    720000
 1    720000
 Name: count, dtype: int64,
 class
 0    180000
 1    180000
 Name: count, dtype: int64)

In [8]:
cleaned=[]

In [9]:
train_df['reviewText'].apply(lambda x:clean_text(x))

777874     None
437088     None
1682677    None
258398     None
532783     None
           ... 
517030     None
1159147    None
141851     None
470786     None
1442462    None
Name: reviewText, Length: 1440000, dtype: object

In [10]:
train_list=cleaned

In [11]:
train_list

[['very',
  'good',
  'workgroup',
  'switch',
  'it',
  'seems',
  'it',
  'imporved',
  'my',
  'connection',
  'lot',
  'better',
  'and',
  'took',
  'huge',
  'load',
  'off',
  'my',
  'router',
  'its',
  'self',
  'what',
  'used',
  'to',
  'take',
  'seconds',
  'to',
  'load',
  'webpage',
  'only',
  'takes',
  'like',
  'seconds',
  'now',
  'think',
  'it',
  'imporved',
  'my',
  'connection',
  'to',
  'the',
  'psn',
  'on',
  'ps',
  'witch',
  'my',
  'games',
  'never',
  'did',
  'lag',
  'before',
  'using',
  'this',
  'but',
  'it',
  'has',
  'imporved',
  'the',
  'connection',
  'status',
  'ps',
  'connection',
  'overall',
  'this',
  'is',
  'prefect',
  'plus',
  'the',
  'bandwidth',
  'is',
  'better',
  'then',
  'using',
  'the',
  'standard',
  'modem',
  'router',
  'must',
  'buy',
  'for',
  'those',
  'looking',
  'to',
  'improve',
  'lot',
  'on',
  'there',
  'connection',
  'bandwidth',
  'most',
  'impressed',
  'with',
  'this',
  'product'

In [12]:
cleaned=[]
test_df['reviewText'].apply(lambda x:clean_text(x))
test_list=cleaned

In [13]:
test_list

[['both',
  'shoes',
  'started',
  'coming',
  'apart',
  'after',
  'weeks',
  'of',
  'wear',
  'not',
  'daily',
  'amazon',
  'will',
  'not',
  'make',
  'adjustments',
  'because',
  'the',
  'return',
  'window',
  'has',
  'passed'],
 ['was',
  'really',
  'impressed',
  'with',
  'this',
  'chafing',
  'dish',
  'it',
  'really',
  'high',
  'quality',
  'and',
  'has',
  'smooth',
  'edges',
  'not',
  'those',
  'sharp',
  'stamped',
  'metal',
  'edges',
  'that',
  'cut',
  'it',
  'heavy',
  'and',
  'sturdy',
  'and',
  'has',
  'great',
  'finish',
  've',
  'used',
  'it',
  'twice',
  'at',
  'our',
  'last',
  'two',
  'parties',
  'it',
  'has',
  'great',
  'heavy',
  'duty',
  'lid',
  'and',
  'serves',
  'up',
  'food',
  'with',
  'style',
  'highly',
  'recommend',
  'this',
  'chafing',
  'dish',
  'quarts',
  'is',
  'definitely',
  'the',
  'right',
  'size',
  'to',
  'go',
  'with'],
 ['bought',
  'this',
  'game',
  'on',
  'recommendation',
  'but',
  

In [14]:
word2vec_model = Word2Vec(window=5,min_count=2,vector_size=300)

In [15]:
word2vec_model.build_vocab(train_list)

In [16]:
word2vec_model.train(train_list,total_examples=word2vec_model.corpus_count,epochs=word2vec_model.epochs)

(388273436, 514518845)

In [17]:
word2vec_model.wv.most_similar('animal')

[('animals', 0.7029314637184143),
 ('giraffe', 0.5953801274299622),
 ('owl', 0.5893310308456421),
 ('elmo', 0.5559986233711243),
 ('webkinz', 0.5551312565803528),
 ('penguin', 0.5542741417884827),
 ('octopus', 0.5531706809997559),
 ('pig', 0.5406323671340942),
 ('pet', 0.5398291945457458),
 ('critter', 0.5373029708862305)]

In [18]:
word2vec_model.wv.key_to_index['animal']

2402

In [19]:
word2vec_model.wv['animal']

array([-1.2583133 ,  2.0169318 , -1.0359716 ,  0.93095404, -0.3205507 ,
        0.35448992,  1.0042727 ,  0.6993296 , -0.29253885, -0.47722253,
       -0.19132017,  1.052188  , -1.556318  , -1.0525422 ,  1.2553656 ,
       -0.7545169 ,  0.04787688, -0.5559507 ,  0.47735023, -2.2183745 ,
       -1.088934  ,  0.67688173,  0.6772245 ,  2.938057  , -0.00785665,
        0.7619374 , -0.09885633,  1.0149907 , -1.434364  , -0.9157099 ,
        0.25951535, -0.5847063 , -0.2581118 , -1.394602  ,  0.58442986,
        0.31264016, -1.1410096 , -1.2846696 ,  0.9403425 ,  0.42856422,
        1.1083629 , -0.3643036 ,  2.1624222 , -0.2365473 ,  0.50588083,
       -0.3255354 ,  1.3969872 , -0.03624836, -0.02417322, -1.3899171 ,
        0.09373199,  2.5402591 , -0.45171455, -1.1951238 ,  0.8342242 ,
        1.5812982 , -0.22266965, -1.0684136 ,  1.0874964 ,  0.07827082,
        1.9538074 ,  1.3759059 ,  1.670316  ,  0.37399858, -2.624046  ,
        0.94641805, -0.1816884 , -1.2723045 ,  2.0078819 ,  1.52

In [20]:
df_temp=df

In [21]:
max_sequence_length=300

In [22]:
# Convert words to Word2Vec embeddings
embedding_matrix = np.zeros((len(word2vec_model.wv.key_to_index) + 1,word2vec_model.vector_size))
for word, i in word2vec_model.wv.key_to_index.items():
    embedding_vector = word2vec_model.wv[word]
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

In [23]:
embedding_matrix.shape

(129093, 300)

In [24]:
# Convert text data to sequences of Word2Vec indices
def convert_to_indices(sentence_list):
    sequences = []
    for sentence in sentence_list:
        sequence = []
        for word in sentence:
            if word in word2vec_model.wv:
                sequence.append(word2vec_model.wv.key_to_index[word])
        sequences.append(sequence)
    return sequences

In [25]:
train_seq = convert_to_indices(train_list)
test_seq = convert_to_indices(test_list)

In [26]:
# Pad sequences to ensure uniform length
padded_train_sequences = pad_sequences(train_seq, maxlen=max_sequence_length, padding='post')
padded_test_sequences = pad_sequences(test_seq, maxlen=max_sequence_length, padding='post')


In [27]:
padded_train_sequences

array([[   24,    40, 26467, ...,     0,     0,     0],
       [   33,     1,    53, ...,     0,     0,     0],
       [70289,   717,     4, ...,     0,     0,     0],
       ...,
       [    5,     4,     0, ...,     0,     0,     0],
       [  206,     5,   129, ...,     0,     0,     0],
       [    7,    52,    32, ...,     0,     0,     0]])

In [28]:
padded_test_sequences

array([[  210,   299,   362, ...,     0,     0,     0],
       [   16,    67,   826, ...,     0,     0,     0],
       [   58,     5,   239, ...,     0,     0,     0],
       ...,
       [13637,    62,   385, ...,     0,     0,     0],
       [   58,    38,  3050, ...,     0,     0,     0],
       [  105,    28,  8638, ...,     0,     0,     0]])

In [30]:
lstm_model=tf.keras.models.Sequential()
lstm_model.add(tf.keras.layers.Embedding(
                    input_dim=len(word2vec_model.wv.key_to_index) +  1,
                    output_dim=word2vec_model.vector_size, 
                    weights=[embedding_matrix],
                    input_length=max_sequence_length,
                    trainable=False))
lstm_model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))
lstm_model.add(tf.keras.layers.Dense(32,activation='relu'))
lstm_model.add(tf.keras.layers.Dense(16,activation='relu'))
lstm_model.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [31]:
lstm_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [32]:
lstm_model.fit(padded_train_sequences,train_df['class'],epochs=5,validation_data=[padded_test_sequences,test_df['class']],batch_size=64)

Epoch 1/5
22500/22500 [==============================] - 1260s 56ms/step - loss: 0.2845 - accuracy: 0.8814 - val_loss: 0.2632 - val_accuracy: 0.8934
Epoch 2/5
22500/22500 [==============================] - 1258s 56ms/step - loss: 0.2521 - accuracy: 0.8971 - val_loss: 0.2527 - val_accuracy: 0.8967
Epoch 3/5
22500/22500 [==============================] - 1263s 56ms/step - loss: 0.2458 - accuracy: 0.9003 - val_loss: 0.2493 - val_accuracy: 0.8986
Epoch 4/5
17667/22500 [======================>.......] - ETA: 3:59 - loss: 0.2423 - accuracy: 0.9018

KeyboardInterrupt: 

In [ ]:
#sentence prediction
sent = """Firstly product’s dimensions is very small against as shown in the description.
Secondly product’s design is not a appropriate to be used as per intended. Objects of all shapes can be fitted in other shapes. Child cannot match the object to its shape which defeats the purpose of this product."""


In [ ]:
def clean_text_for_prediction(sent):
    sent_list=simple_preprocess(sent)
    sequence = []
    for word in sent_list:
        if word in word2vec_model.wv:
            sequence.append(word2vec_model.wv.key_to_index[word])
    return sequence


In [ ]:
sent_seq = clean_text_for_prediction(sent)
padded_sequences = pad_sequences([sent_seq], maxlen=max_sequence_length, padding='post')


In [ ]:
padded_sequences

array([[6878,   51, 2489,    4,   24,  110,  808,   18, 1266,    9,    0,
         601, 3864,   51,  271,    4,   13, 2327,    3,   23,   88,   18,
        1035, 1437, 3249,    6,   31, 2808,   30,   23, 3012,    9,   64,
        2808,  552,  455, 1083,    0, 3571,    3,  105,  700,   70, 4312,
           0,  831,    6,    5,   51,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0, 

In [ ]:
res=lstm_model.predict(padded_sequences)
if res>0.5:
    print('spam')
else:
    print('non spam')

1/1 [==============================] - 0s 34ms/step
non spam


In [ ]:
res

array([[0.9946635]], dtype=float32)

In [ ]:
lstm_model.save('D:\CDAC_PUNE_PROJECT\CDAC_Group_Project\\Training\lstm_model4.h5')

In [ ]:
joblib.dump(lstm_model.get_weights(), "lstm_model_weights4.joblib")

['lstm_model_weights4.joblib']

In [ ]:
lstm_model.save_weights('D:\CDAC_PUNE_PROJECT\CDAC_Group_Project\Training\\lstm_model_weights4.h5')